name: OCR-project

services:
  app:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    env_file: .env
    platform: linux/amd64
    container_name: '${COMPOSE_PROJECT_NAME}'
    hostname: app
    volumes:
      - OCR-project-data:/data
    networks:
      - OCR-project-net
    ports:
      - 8000:8000

volumes:
  OCR-project-data:

networks:
  OCR-project-net:
